{{- if not .Values.global.suspend }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-serving.fullname" . }}
  labels:
     {{- include "llm-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "llm-serving.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.networking.port.number }}
    protocol: TCP
    targetPort: {{ .Values.networking.port.number }}
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end}}
{{- end}}